#!/bin/sh

echo "Iniciando a criação do instalador para Linux"

#if [ -d "temp" ]; then

#	rm -R "temp"

#fi

mkdir "temp"

echo "Compilando o Portugol Studio"
echo "Esta tarefa pode levar alguns minutos, por favor aguarde"

#ant -buildfile ../../Portugol-Studio/build.xml distribuicao > /dev/null

echo "Compilação finalizada"
echo "Configurando arquivos de instalação"

cp -R ../arquivos/bin temp/bin
rm -f temp/bin/launch.jnlp
rm -f temp/bin/launch.html

cp portugol-studio.desktop temp
cp portugol-studio.png temp

echo "Comprimindo arquivos de instalação"

tar -czf "dados.tar.gz" -C temp . > /dev/null

rm -R temp/*
mv dados.tar.gz temp

echo "Criando instalador"

cp instalar temp
echo "" >> temp/instalar
echo "[DADOS]" >> temp/instalar

base64 < temp/dados.tar.gz >> temp/instalar

rm temp/dados.tar.gz
echo "Concluído"
#rm -R "temp"
#rm -R "dist"
