#!/bin/sh

echo "Iniciando a criação do instalador para Linux"

if [ -d "temp" ]; then

	rm -R "temp"
fi

if [ -d "dist" ]; then

	rm -R "dist"

fi

mkdir "temp"

echo "Compilando o Portugol Studio"
echo "Esta tarefa pode levar alguns minutos, por favor aguarde"

ant -buildfile ../../Portugol-Studio/build.xml distribuicao > /dev/null

echo "Compilação finalizada"
echo "Configurando arquivos de instalação"

mv ../arquivos/bin temp
rm -f temp/bin/launch.jnlp
rm -f temp/bin/launch.html

cp portugol-studio.desktop temp
cp portugol-studio.png temp
cp ../arquivos/licenca.txt temp
cp iniciar temp/bin/iniciar
cp desinstalar temp

echo "Comprimindo arquivos de instalação"

cd temp
zip -r -9 ../dados.zip . > /dev/null
cd ..

rm -R temp/*
mv dados.zip temp

echo "Criando instalador"

cp instalar temp
echo "" >> temp/instalar
echo "DADOS:" >> temp/instalar

cat temp/dados.zip >> temp/instalar

rm temp/dados.zip
mv "temp" "dist"
mv "dist/instalar" "dist/instalar-ps-linux"

echo "Concluído"

